在ray_ex.lean中添加了六个需要证明的小定理
jjdishere/EG pull request #101
Opened 2023-09-23 09:03 UTC by XintaoYu

2023-09-23 18:13 UTC, jjdishere requested changes

2023-09-23 18:13 UTC, jjdishere commented on EuclideanGeometry/Foundation/Axiom/Linear/Ray_ex.lean
> +theorem lies_on_iff_lies_on_rev_of_same_todir {ray₁ ray₂ : Ray P} (h : ray₁.toDir = ray₂.toDir) : ray₁.source LiesOn ray₂ ↔ ray₂.source LiesOn ray₁.reverse := sorry
`same` should be `eq`

2023-09-23 18:14 UTC, jjdishere commented on EuclideanGeometry/Foundation/Axiom/Linear/Ray_ex.lean
> +theorem lies_on_iff_lies_on_rev_of_same_todir {ray₁ ray₂ : Ray P} (h : ray₁.toDir = ray₂.toDir) : ray₁.source LiesOn ray₂ ↔ ray₂.source LiesOn ray₁.reverse := sorry
also occurs in the next theorem

2023-09-24 17:21 UTC, jjdishere commented
If you finished your change, please leave a comment here to ask for a new review. Otherwise I won't start to look at your changes. Thanks!

2023-09-25 14:02 UTC, XintaoYu commented on EuclideanGeometry/Foundation/Axiom/Linear/Ray_ex.lean
> +theorem lies_on_iff_lies_on_rev_of_same_todir {ray₁ ray₂ : Ray P} (h : ray₁.toDir = ray₂.toDir) : ray₁.source LiesOn ray₂ ↔ ray₂.source LiesOn ray₁.reverse := sorry
收到，已修改

2023-09-28 07:19 UTC, closed without merging